Add automatic seed creation
engagor/migraine pull request #1
Opened 2022-01-28 08:06 UTC by BenSeDev

This PR will allow you to create a seed file in the same way as you create a migration file.

Similar to creating a new migration file:
vendor/bin/migraine new db_name "description which becomes the file name"

With this update you'll be able to run the following:
vendor/bin/migraine new-seed db_name "description which becomes the file name"

It will then create the seed file inside the appropriate seeds folder inside the folder named after the DB.

2022-01-28 09:36 UTC, cedricengagor reviewed
Wouldn't it make sense if we took the approach:
```sh
migraine new migration test "create user table"
migraine new seed test "default user"
```

This would basically follow the pattern:
`migraine {action=new} {type=seed} {group=test} {name="default user"}`

2022-01-31 08:21 UTC, BenSeDev commented
> Wouldn't it make sense if we took the approach:
> 
> ```shell
> migraine new migration test "create user table"
> migraine new seed test "default user"
> ```
> 
> This would basically follow the pattern: `migraine {action=new} {type=seed} {group=test} {name="default user"}`

Done Ancient One.

2022-01-31 13:12 UTC, matthias-deschoenmacker approved these changes

2022-02-01 08:09 UTC, cedricengagor approved these changes

2022-02-01 08:09 UTC, cedricengagor commented on src/NewSeed.php
> +        if (!is_dir($seedPath)) {
```suggestion
        if (!is_dir($seedPath)) {
```

2022-02-02 09:51 UTC, BenSeDev commented
@matthias-deschoenmacker & @cedricengagor 

An addition to the PR: Allowing a `--seed` option to the migrate command.
Which will execute all the seed files & log them in the logs.json

2022-02-02 14:15 UTC, cedricengagor requested changes
Nice work, perhaps a unit test?

2022-02-02 14:15 UTC, cedricengagor commented on src/SeedUp.php
> +    public function seedUp(bool $commit = false, string $onlyMigrateThisGroup = ''): CompletedSeeds
Unit test?

2022-02-03 10:35 UTC, BenSeDev commented on src/CommandSeed.php
>          $listOfCompletedMigrations = $completedMigrations->getList();
Done

2022-02-03 10:36 UTC, BenSeDev commented on src/SeedUp.php
> +    public function seedUp(bool $commit = false, string $onlyMigrateThisGroup = ''): CompletedSeeds
Sure thing Ancient One

2022-02-03 16:20 UTC, cedricengagor reviewed
1 more Q, but nice work. Looking forward to this 👏

2022-02-03 16:20 UTC, cedricengagor commented on src/LogsSQL.php
> +                in_array($event['event'], [EventSeedWasExecuted::class, EventMigrationWasSkipped::class])
Q: Do we need to check for migration was skipped here? I think this can 🔥 ?

2022-02-03 16:20 UTC, cedricengagor commented on src/LogsSQL.php
> +        $query = "SELECT * FROM `{$strategy->getTable()}`";
```suggestion
        $query = "SELECT `event` FROM `{$strategy->getTable()}`";
```

Looking from the code it seemed that only `event` was used. (but best to double check). It is always better to specify the required columns here, both for readability and to reduce bandwidth

2022-02-04 08:59 UTC, BenSeDev commented on src/LogsSQL.php
> +        $query = "SELECT * FROM `{$strategy->getTable()}`";
So this was a copy pasta, but indeed, for the seeds we're only checking for the event, so, you ask wij draaien eh.

2022-02-04 09:02 UTC, BenSeDev commented on src/LogsSQL.php
> +                in_array($event['event'], [EventSeedWasExecuted::class, EventMigrationWasSkipped::class])
You've passed the test Ancient One. 
Eternal fame for noticing, 🤣

2022-02-07 08:06 UTC, cedricengagor approved these changes

2022-02-07 08:58 UTC, matthias-deschoenmacker approved these changes
LGTM

2022-02-07 12:43 UTC, merged